### ISSUE TITLE
Config values don't have a default value.

### ISSUE THREAD

**Issue by galgalesh** [cmars/layer-lets-encrypt#4]
Charms using this layer get a `charm proof` warning because config values don't have a default value.

warning:

```
proof: W: config.yaml: option contact-email does not have the keys: default
```

source:

```yaml
  fqdn:                       
    type: string               
    description: Fully-Qualified Domain Name of server to register
  contact-email:
    type: string
    description: Contact email for Let's Encrypt
```

This is currently a blocker for promulgating charms using this layer.
